### ISSUE TITLE
KeyError: 'images'

### ISSUE THREAD

**Issue by daveckw** [nerdyrodent/StableBot#2]
File "E:\Stable Diffussion\one-click-installers\text-generation-webui\extensions\sd_api_bot\script.py", line 90, in get_SD_pictures
    for img_str in r['images']:
KeyError: 'images'

I got above when i enable the extension.

**Comment by k99goran** [comment]
I got the same error whenever I click "Generate". The text never generates, and the bot just pauses.

**Comment by xektop** [comment]
@daveckw @k99goran put --api into your Automatic1111 bat file
For example mine reads:
@echo off

set PYTHON=
set GIT=
set VENV_DIR=
set COMMANDLINE_ARGS= --listen --api --enable-insecure-extension-access --opt-sdp-attention --port 7861


call webui.bat

**Comment by daveckw** [comment]
> @daveckw @k99goran put --api into your Automatic1111 bat file For example mine reads: @echo off
> 
> set PYTHON= set GIT= set VENV_DIR= set COMMANDLINE_ARGS= --listen --api --enable-insecure-extension-access --opt-sdp-attention --port 7861
> 
> call webui.bat

This works. Thank you.
