### ISSUE TITLE
Every image reply come in a few image... not just one image...

### ISSUE THREAD

**Issue by SauChi666** [nerdyrodent/StableBot#4]
Every image reply comes in 3 images... Not one... and the system become slow, how can I change it to 1 reply

**Comment by TheRealBlackNet** [comment]
Had the problem too, Do you run only "sd_api_bot" or also "ad_api_pictures" for this repo you only need "sd_api_bot" active.

**Comment by nerdyrodent** [comment]
Don't use streaming
